### ISSUE TITLE
Implement a "feature testing" and not a browser testing.

### ISSUE THREAD

**Issue by altryne** [joelambert/Flux-Slider#1]
As soon as firefox 4, ie10 and others start supporting css animations/transitions, the code that checks only for webkit engine will start to fail.
Instead can check for the specific set of functions modernizr style and if all checks pass, let users see the flux.

**Comment by joelambert** [comment]
This is planned for a future release, it didn't make 1.0 due to time constraints.

The flux.browser object already detects 3d support which is used to ensure translate3d() is used over translate() where its supported. 

To check the browser is compliant, do you think its adequate to just check for CSS3 transform support? I'll take a look and see how modernizr handles this

**Comment by joelambert** [comment]
I've added feature detection and some helper functions that work under both jQuery and Zepto:

`.css3()` - adds all the vendor prefixes to css3 properties
`.transitionEnd()` - sets up an event listener for the 'transition end' event for each vendor.

The current code in the repo (v1.2) now supports Firefox 4 (albeit, the `border-radius` in the concentric transition isn't working?)
